
all:
	@make test

test:
	@( echo 'run the test suite...' )

watch:
	@( grunt test jshint watch )

deploy:
	@( echo 'deploy the application...' )

.PHONY: test
.PHONY: watch
.PHONY: version
.PHONY: deploy

